CREATE DATABASE IF NOT EXISTS webgui;

USE webgui;

CREATE TABLE IF NOT EXISTS registration (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    course VARCHAR(100) NOT NULL,
    fee VARCHAR(20) NOT NULL
);
